
;; NOTE: ESS needs to be before org-mode

(load "~/.emacs.misenplace/packages/mep-all-the-icons.el")
(load "~/.emacs.misenplace/packages/mep-affe.el")
(load "~/.emacs.misenplace/packages/mep-bash-completion.el")
(load "~/.emacs.misenplace/packages/mep-consult.el")
(load "~/.emacs.misenplace/packages/mep-corfu.el")
(load "~/.emacs.misenplace/packages/mep-dashboard.el")
(load "~/.emacs.misenplace/packages/mep-doom-modeline.el")
(load "~/.emacs.misenplace/packages/mep-ess.el")
(load "~/.emacs.misenplace/packages/mep-evil-collection.el")
(load "~/.emacs.misenplace/packages/mep-evil.el")
(load "~/.emacs.misenplace/packages/mep-flycheck.el")
(load "~/.emacs.misenplace/packages/mep-gptel.el")
(load "~/.emacs.misenplace/packages/mep-grip-mode.el")
(load "~/.emacs.misenplace/packages/mep-htmlize.el")
(load "~/.emacs.misenplace/packages/mep-lsp-bridge.el")
(load "~/.emacs.misenplace/packages/mep-lsp-mode.el")
(load "~/.emacs.misenplace/packages/mep-lsp-ui.el")

(load "~/.emacs.misenplace/packages/mep-lsp-java.el")

(load "~/.emacs.misenplace/packages/mep-marginalia.el")
(load "~/.emacs.misenplace/packages/mep-markdown-mode.el")
(load "~/.emacs.misenplace/packages/mep-neotree.el")
(load "~/.emacs.misenplace/packages/mep-orderless.el")
(load "~/.emacs.misenplace/packages/mep-org-mode.el")
(load "~/.emacs.misenplace/packages/mep-org-gtd.el")
(load "~/.emacs.misenplace/packages/mep-org-roam.el")
(load "~/.emacs.misenplace/packages/mep-org-reveal.el")
(load "~/.emacs.misenplace/packages/mep-org-preview-html.el")
(load "~/.emacs.misenplace/packages/mep-projectile.el")
(load "~/.emacs.misenplace/packages/mep-treemacs.el")
(load "~/.emacs.misenplace/packages/mep-vertico.el")
(load "~/.emacs.misenplace/packages/mep-which-key.el")
(load "~/.emacs.misenplace/packages/mep-yasnippet.el")
(load "~/.emacs.misenplace/packages/mep-zenmode.el")
(load "~/.emacs.misenplace/packages/mep-ivy.el")

(load "~/.emacs.misenplace/packages/mep-perspective.el")

(load "~/.emacs.misenplace/packages/mep-general.el")

(load "~/.emacs.misenplace/packages/mep-ob-async.el")
(load "~/.emacs.misenplace/packages/mep-dap-mode.el")

(load "~/.emacs.misenplace/packages/mep-cmake-mode.el")
(load "~/.emacs.misenplace/packages/mep-ox-gfm.el")
(load "~/.emacs.misenplace/packages/mep-ob-mermaid.el")

(load "~/.emacs.misenplace/packages/mep-anaconda-mode.el")
(load "~/.emacs.misenplace/packages/mep-texfrag.el")
(load "~/.emacs.misenplace/packages/mep-auxtex.el")
(load "~/.emacs.misenplace/packages/mep-vimish-fold.el")
(load "~/.emacs.misenplace/packages/mep-org-modern.el")

(load "~/.emacs.misenplace/packages/mep-magit.el")

(load "~/.emacs.misenplace/packages/mep-magit.el")
(load "~/.emacs.misenplace/packages/mep-golden-ratio.el")

;; (load "~/.emacs.d/packages/mep-eaf.el")
;; (load "~/.emacs.d/packages/mep-lsp-mode.el")
;; (load "~/.emacs.d/packages/mep-company.el")
;; (load "~/.emacs.d/packages/mep-git-gutter.el")
;; (load "~/.emacs.d/packages/mep-editorconfig.el")
;; (load "~/.emacs.d/packages/mep-hl-todo.el")
;; (load "~/.emacs.d/packages/mep-counsel.el")
;; (load "~/.emacs.d/packages/mep-apropospriate-theme.el")
;; ;; (load "~/.emacs.d/packages/mep-ivy.el")
