

(load "~/.emacs.d/packages/mep-hl-todo.el")
(load "~/.emacs.d/packages/mep-git-gutter.el")
(load "~/.emacs.d/packages/mep-which-key.el")
(load "~/.emacs.d/packages/mep-affe.el")
(load "~/.emacs.d/packages/mep-all-the-icons.el")
(load "~/.emacs.d/packages/mep-apropospriate-theme.el")
(load "~/.emacs.d/packages/mep-company.el")
(load "~/.emacs.d/packages/mep-consult.el")
(load "~/.emacs.d/packages/mep-corfu.el")
(load "~/.emacs.d/packages/mep-counsel.el")
(load "~/.emacs.d/packages/mep-dashboard.el")
(load "~/.emacs.d/packages/mep-doom-modeline.el")
(load "~/.emacs.d/packages/mep-ess.el")
(load "~/.emacs.d/packages/mep-evil-collection.el")
(load "~/.emacs.d/packages/mep-evil.el")
(load "~/.emacs.d/packages/mep-general.el")
(load "~/.emacs.d/packages/mep-gptel.el")
(load "~/.emacs.d/packages/mep-htmlize.el")
;; (load "~/.emacs.d/packages/mep-ivy.el")
(load "~/.emacs.d/packages/mep-lsp-mode.el")
(load "~/.emacs.d/packages/mep-lsp-java.el")
(load "~/.emacs.d/packages/mep-marginalia.el")
(load "~/.emacs.d/packages/mep-neotree.el")
;; (load "~/.emacs.d/packages/mep-ob-async.el")
(load "~/.emacs.d/packages/mep-orderless.el")
(load "~/.emacs.d/packages/mep-org-mode.el")
(load "~/.emacs.d/packages/mep-perspective.el")
(load "~/.emacs.d/packages/mep-projectile.el")
(load "~/.emacs.d/packages/mep-vertico.el")
(load "~/.emacs.d/packages/mep-yasnippet.el")
(load "~/.emacs.d/packages/mep-flycheck.el")
(load "~/.emacs.d/packages/mep-treemacs.el")
